### ISSUE TITLE
Panic listing operators

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nsc#31]
This may have been fixed in more recent version. For tracking purposes.
```
IvanMBP:ngs ivan$ ngs --version
ngs version 0.2.3
```
Signed up with free account, then:
```
IvanMBP:ngs ivan$ ngs list operators
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130bc25]

goroutine 1 [running]:
github.com/nats-io/jwt.(*GenericClaims).Claims(0x0, 0xc0001a2080)
    /home/travis/gopath/pkg/mod/github.com/nats-io/jwt@v0.0.5/genericlaims.go:33 +0x5
github.com/nats-io/nsc/cmd.listEntities(0x169e4b0, 0x9, 0xc00009a778, 0x1, 0x1, 0xc000098fd6, 0x7, 0x1, 0xc0001a2000)
    /home/travis/gopath/pkg/mod/github.com/nats-io/nsc@v0.0.0-20181206000536-9c7a9fd3e169/cmd/listoperators.go:177 +0x529
github.com/nats-io/nsc/cmd.createListOperatorsCmd.func1(0xc00017e280, 0x1bb6400, 0x0, 0x0, 0x0, 0x0)
    /home/travis/gopath/pkg/mod/github.com/nats-io/nsc@v0.0.0-20181206000536-9c7a9fd3e169/cmd/listoperators.go:69 +0x2ae
github.com/spf13/cobra.(*Command).execute(0xc00017e280, 0x1bb6400, 0x0, 0x0, 0xc00017e280, 0x1bb6400)
    /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x1b8e9e0, 0xc00009a010, 0x1743340, 0xc00009a010)
    /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1b8e9e0, 0x1743340, 0xc00009a010)
    /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
    /home/travis/gopath/src/github.com/ConnectEverything/ngs/ngs/main.go:55 +0x276
```

**Comment by aricart** [comment]
with current version of nsc embedded in ngs:

```synadia malaga:~ [5001]% which ngs
/Users/synadia/Dropbox/code/bin/ngs
synadia malaga:~ [5002]% ngs describe operator
Error: no operator "synadia" found
synadia malaga:~ [5003:1]% ngs list operators
╭───────────────────────────────────────────────────────╮
│                       Operators                       │
├─────────┬─────────────────────────────────────────────┤
│ Name    │ Public Key                                  │
├─────────┼─────────────────────────────────────────────┤
│ synadia │ error loading jwt - "synadia" jwt not found │
╰─────────┴─────────────────────────────────────────────╯

synadia malaga:~ [5004]% 
```

The operator jwt for synadia has to be renamed.

**Comment by aricart** [comment]
Opened an issue on the ngs side.
