### ISSUE TITLE
invalid memory address or nil pointer dereference (cmd/push.go:150)

### ISSUE THREAD

**Issue by mullerch** [nats-io/nsc#403]
I get this error when trying to `nsc push -A`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9132a7]

goroutine 1 [running]:
github.com/nats-io/nsc/cmd.getSystemAccountUser(0xb25928, 0xc00021f050, 0xc000268278, 0x3, 0x0, 0x0, 0xa5bd16, 0x8, 0xc000263b98, 0x3, ...)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/push.go:150 +0x807
github.com/nats-io/nsc/cmd.(*PushCmdParams).Run(0xc000170630, 0xb25928, 0xc00021f050, 0x0, 0x0, 0x0, 0x0)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/push.go:544 +0x745
github.com/nats-io/nsc/cmd.run(0xb25928, 0xc00021f050, 0xa22c20, 0xc000170630, 0xb25928, 0xc00021f050)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/action.go:144 +0x186
github.com/nats-io/nsc/cmd.RunAction(0xc000212500, 0xc00022a120, 0x0, 0x1, 0xa22c20, 0xc000170630, 0x0, 0x0)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/action.go:112 +0xa5
github.com/nats-io/nsc/cmd.createPushCmd.func1(0xc000212500, 0xc00022a120, 0x0, 0x1, 0x0, 0x0)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/push.go:47 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc000212500, 0xc00022a100, 0x1, 0x1, 0xc000212500, 0xc00022a100)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/vendor/github.com/spf13/cobra/command.go:762 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xe1b7c0, 0xc000098000, 0x0, 0x0)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/vendor/github.com/spf13/cobra/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/vendor/github.com/spf13/cobra/command.go:800
github.com/nats-io/nsc/cmd.ExecuteWithWriter(0xb17880, 0xc00000e020, 0xc00000e020, 0xb17880)
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/root.go:185 +0x52
github.com/nats-io/nsc/cmd.Execute()
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/cmd/root.go:173 +0x5d
main.main()
        /Users/aricart/Dropbox/code/src/github.com/nats-io/nsc/main.go:19 +0x131
```

This is a typical oprator > account > user setup with a SYS account. I was able to push it once, deleted a nkey, made some other actions and could not push it again.

I guess this should be quite straightforward to find out with the stack but if it's not I can try to find a reproduction scenario, just let me know.

nsc --version
nsc version 2.2.6

**Comment by aricart** [comment]
@mullerch thanks for the report.  This nsc was installed via the installer?

**Comment by mullerch** [comment]
`curl -L https://raw.githubusercontent.com/nats-io/nsc/master/install.py | python`

With python 3.

**Comment by variadico** [comment]
Resolved via https://github.com/nats-io/nsc/pull/404
