### ISSUE TITLE
Not able to install nsc on windows machine

### ISSUE THREAD

**Issue by WAG10** [nats-io/nsc#629]
### What version were you using?

Not applicable

### What environment was the server running in?

Windows 

### Is this defect reproducible?

Not sure

### Given the capability you are leveraging, describe your expectation?

We should be able to install nsc on windows machine

### Given the expectation, what is the defect you are observing?

once we run the command to install nsc we get below error:
Microsoft Windows [Version 10.0.17763.5122]
(c) 2018 Microsoft Corporation. All rights reserved.

**C:\Users\winuser>curl -L https://raw.githubusercontent.com/nats-io/nsc/master/install.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5307  100  5307    0     0  24654      0 --:--:-- --:--:-- --:--:-- 25271
Traceback (most recent call last):
  File "<stdin>", line 195, in <module>
  File "<stdin>", line 94, in main
AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?**

**Comment by WAG10** [comment]
Thanks a ton @aricart !!
This worked.
